prooph_event_store:
  stores:
    user_store:
      adapter: 'prooph_event_store.doctrine_adapter.user_store'
      repositories:
          user_repository:
              repository_class: 'UserIdentity\Infrastructure\Persistence\EventStoreUserRepository'
              aggregate_type: 'UserIdentity\Domain\Model\User'
              aggregate_translator: 'prooph_event_sourcing.aggregate_translator'

          publisher_repository:
              repository_class: 'UserIdentity\Infrastructure\Persistence\EventStorePublisherRepository'
              aggregate_type: 'UserIdentity\Domain\Model\Publisher'
              aggregate_translator: 'prooph_event_sourcing.aggregate_translator'

services:
  prooph_event_store.doctrine_adapter.user_store:
    class: Prooph\EventStore\Adapter\Doctrine\DoctrineEventStoreAdapter
    arguments: ['@doctrine.dbal.default_connection', '@prooph_event_store.message_factory', '@prooph_event_store.message_converter', '@prooph_event_store.payload_serializer', '%prooph_event_store.stream_table_map%']

  'prooph_event_sourcing.aggregate_translator':
      class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

  'prooph_event_store_bus_bridge.transaction_manager':
      class: Prooph\EventStoreBusBridge\TransactionManager
      tags:
        - { name: 'prooph_event_store.user_store.plugin' }

  'prooph_event_store_bus_bridge.user_event_publisher':
      class: Prooph\EventStoreBusBridge\EventPublisher
      arguments: ['@prooph_service_bus.user_event_bus']
      tags:
        - { name: 'prooph_event_store.user_store.plugin' }